version: '3.8'
services:
  musetalk:
    build: .
    image: musetalk:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - FFMPEG_PATH=/app/ffmpeg
    volumes:
      - ./data:/app/data  # Map a local data directory to the container
    working_dir: /app
    command: bash

