avator_1:
 preparation: True
 bbox_shift: 7
 video_path: "/app/vllm/virtualhumans/MuseTalk/data/video/left_avatar_talking.mp4"
 audio_clips:
     audio_0: "/app/vllm/virtualhumans/MuseTalk/data/audio/obama.wav" 
